### ISSUE TITLE
exec format error when running docker-compose

### ISSUE THREAD

**Issue by KingKahn123** [weidi/stream2giratksip#1]
Hi,

when running docker-compose on my raspberry pi with newest Bullseye I get following error message:

exec /usr/bin/docker-entrypoint.sh: exec format error

Is it because the docker file is intended for Debian11 and not for the raspberry OS?

**Comment by weidi** [comment]
I think i only built this for x86 systems so no ARM support for the container on dockerhub but you can easily build the container your own and reference your local one in the docker compose file.

**Comment by KingKahn123** [comment]
I have changed the image to "armv32v7/alpine" in the Dockerfile and created a new container image. However, I still have some problems with the "docker-entrypoint.sh" file. Wenn starting the container I get following error message:

"ERROR: for 4638cbdaabcc_unifi2gira2_stream2giratksipKAI_1  Cannot start service stream2giratksi                        pKAI: failed to create shim task: OCI runtime create failed: runc create failed: unable to star                        t container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown

ERROR: for stream2giratksipKAI  Cannot start service stream2giratksipKAI: failed to create shim                         task: OCI runtime create failed: runc create failed: unable to start container process: exec:                         "docker-entrypoint.sh": executable file not found in $PATH: unknown"

Any hint what the problem is?

**Comment by weidi** [comment]
Seems weird as if /usr/bin is not part of $PATH so please add it in line 6 of DOCKERFILE
`/usr/bin/docker-entrypoint.sh`
also make sure you are using alpine 3.8 because ffserver willt not work on later releases

**Comment by KingKahn123** [comment]
ok the container is now starting, after making the docker-entrypoint.sh executable. But then it immediately stops with following error:

bind(port 8090): Address not available
Mon Jun 27 07:15:14 2022 Could not start server

The port is not used by another application. Seems some network problems?

**Comment by weidi** [comment]
seems like the container networking is not working correctly, i never played around on ARM but i was expecting it´s working the same way. Need to check. You could try changing the port and see if it works but i doubt it.

**Comment by KingKahn123** [comment]
Yes I have changed the port now to 8091... But although I have changed it in the Dockerfile and the docker-entrypoint.sh it is still trying to bind 8090 and therefore exists with same error. Is this port configured somewhere else?

**Comment by KingKahn123** [comment]
Do you had a chance to have a look into issue? Any wishlist on Amazon I can support? 😁

**Comment by weidi** [comment]
Just updated all the files, seems i had CRLF as line ending and linux doesn´t like it ;) Please try it now, i will play around to see wheter i can build an arm version without an ARM device at hand.

**Comment by KingKahn123** [comment]
Very cool... It is now running! Thank you very much!

**Comment by weidi** [comment]
Great to hear that, I was able to also build armv7 and arm64 images so you can just pull it from dockerhub ;)
